/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.csrfdemo.transferservice.controller;

import com.csrfdemo.transferservice.TransferService;
import java.lang.Integer;
import java.lang.Double;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/transfer")
public class TransferController {

    @Autowired
    private TransferService transferService;

    @RequestMapping(value = "/transfer", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public Double setTransfer(@RequestParam(value = "fromAcId", required = false) Integer fromAcId, @RequestParam(value = "toAcId", required = false) Integer toAcId, @RequestParam(value = "amount", required = false) Double amount) {
        return transferService.setTransfer(fromAcId, toAcId, amount);
    }
}
